/** LeptonSplit contract ABI — keep in sync with contracts/LeptonSplit.sol */
export const leptonSplitAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_platformWallet", type: "address" }],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "platformWallet",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STANDARD_CREATOR_BPS",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contentCreator",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contentBps",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tipCreatorBps",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settlementClaimed",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerContentCreator",
    inputs: [
      { name: "contentId", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "bps", type: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerTipCreator",
    inputs: [
      { name: "creator", type: "address" },
      { name: "bps", type: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "splitPayment",
    inputs: [
      { name: "settlementId", type: "bytes32" },
      { name: "contentId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "splitToCreator",
    inputs: [
      { name: "settlementId", type: "bytes32" },
      { name: "creator", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "contractBalance",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SplitPayment",
    inputs: [
      { name: "settlementId", type: "bytes32", indexed: true },
      { name: "contentId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "total", type: "uint256", indexed: false },
      { name: "toCreator", type: "uint256", indexed: false },
      { name: "toPlatform", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SplitTip",
    inputs: [
      { name: "settlementId", type: "bytes32", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "total", type: "uint256", indexed: false },
      { name: "toCreator", type: "uint256", indexed: false },
      { name: "toPlatform", type: "uint256", indexed: false },
    ],
  },
] as const;
